<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\YemenDrive.Shared\YemenDrive.Shared.csproj" />
    <ProjectReference Include="..\YemenDrive.Services\YemenDrive.Services.csproj" />
    <ProjectReference Include="..\YemenDrive.Database\YemenDrive.Database.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
